Enhance 60-getweb.in.patch to forbid live update of /usr/bin/getweb as it is packaged.

diff --git a/debian/patches/60-getweb.in.patch b/debian/patches/60-getweb.in.patch
--- a/debian/patches/60-getweb.in.patch
+++ b/debian/patches/60-getweb.in.patch
@@ -24,7 +24,16 @@ Improve getweb also for installing the firmware
  
  usage() {
  cat <<EOF
-@@ -101,7 +108,7 @@
+@@ -85,8 +92,6 @@
+     $ ./getweb all	# Get everything above
+ 
+     $ ./getweb 2300dl_fw # Get Minolta 2300DL v2.55 firmware (experts only)
+-
+-    $ ./getweb update	# Get latest version of this software.
+ EOF
+     exit 1
+ }
+@@ -101,7 +106,7 @@
  }
  
  SYSTEM=`uname -s`
@@ -33,7 +42,7 @@ Improve getweb also for installing the firmware
  if [ "$SYSTEM" = Darwin -a "$WGET" = "" ]
  then
      WGETOPTS=
-@@ -111,6 +118,18 @@
+@@ -111,6 +116,18 @@
      }
  fi
  
@@ -52,7 +61,7 @@ Improve getweb also for installing the firmware
  #
  #	Download a .EXE file from the web, unzip it, and extract the
  #	files we want
-@@ -157,6 +176,7 @@
+@@ -157,6 +174,7 @@
  	    #lj1488en.exe \
  	    #sihp1000.img
  	copyright "(c) Copyright Hewlett-Packard 2001"
@@ -60,7 +69,7 @@ Improve getweb also for installing the firmware
  	;;
      lj1005|1005)
  	gettgz \
-@@ -172,36 +192,42 @@
+@@ -172,36 +190,42 @@
  	    http://foo2zjs.rkkda.com/firmware sihpP1005.tar.gz \
  	    ""
  	copyright "(c) Copyright Hewlett-Packard 2009"
@@ -103,7 +112,7 @@ Improve getweb also for installing the firmware
  	;;
      2200dl|2200)
  	if true; then
-@@ -214,6 +240,7 @@
+@@ -214,6 +238,7 @@
  		"*.icm"
  	fi
  	copyright "(c) Copyright Minolta-QMS 1999"
@@ -111,7 +120,7 @@ Improve getweb also for installing the firmware
  	;;
      2300dl|2300)
  	if true; then
-@@ -229,6 +256,7 @@
+@@ -229,6 +254,7 @@
  	    http://foo2zjs.rkkda.com/icm km2430.tar.gz \
  	    ""
  	copyright "(c) Copyright Minolta-QMS 2001"
@@ -119,7 +128,7 @@ Improve getweb also for installing the firmware
  	;;
      2300dl_fw)
  	# 2300DL firmware upgrade to v2.55
-@@ -257,12 +285,14 @@
+@@ -257,12 +283,14 @@
  	    done
  	fi
  	copyright "(c) Copyright Minolta-QMS 1998"
@@ -134,7 +143,7 @@ Improve getweb also for installing the firmware
  	;;
      2530|2490|6115|2480|1600w|1680|1690|4690|110|6121)
  	gettgz \
-@@ -274,6 +304,7 @@
+@@ -274,6 +302,7 @@
  	    http://foo2lava.rkkda.com/icm km-1600.tar.gz \
  	    ""
  	copyright "(c) Copyright Rick Richardson 2009.  All Rights Reserved"
@@ -142,7 +151,7 @@ Improve getweb also for installing the firmware
  	;;
      1500)
  	gettgz \
-@@ -285,12 +316,14 @@
+@@ -285,12 +314,14 @@
  	    ""
  	copyright "(c) Copyright Hewlett-Packard 2003"
  	copyright "(c) Copyright Rick Richardson 2006.  All Rights Reserved"
@@ -157,7 +166,7 @@ Improve getweb also for installing the firmware
  	;;
      1215|1600|2600*)
  	gettgz \
-@@ -305,6 +338,7 @@
+@@ -305,6 +336,7 @@
  	    http://foo2hp.rkkda.com/icm hp1215.tar.gz \
  	    ""
  	copyright "(c) Copyright Rick Richardson 2008.  All Rights Reserved"
@@ -165,7 +174,7 @@ Improve getweb also for installing the firmware
  	;;
      300|310|315|325|2160|3160|3175|6110)
  	gettgz \
-@@ -315,6 +349,7 @@
+@@ -315,6 +347,7 @@
  	    http://foo2qpdl.rkkda.com/icm samclp315.tar.gz \
  	    ""
  	copyright "(c) Copyright Rick Richardson 2008.  All Rights Reserved"
@@ -173,7 +182,7 @@ Improve getweb also for installing the firmware
  	;;
      600|610)
  	;;
-@@ -324,6 +359,7 @@
+@@ -324,6 +357,7 @@
  	    http://foo2slx.rkkda.com/icm lexc500.tar.gz \
  	    ""
  	copyright "(c) Copyright Lexmark 2006"
@@ -181,7 +190,7 @@ Improve getweb also for installing the firmware
  	;;
  
      oki)
-@@ -339,30 +375,35 @@
+@@ -339,30 +373,35 @@
  	    mv "$base.ICM" "$base.icm"
  	done
  	copyright "(c) Copyright Okidata 2005, 2006"
@@ -217,7 +226,31 @@ Improve getweb also for installing the firmware
  	;;
  
      xPPD)
-@@ -448,6 +489,10 @@
+@@ -417,23 +456,6 @@
+ 		# | sed -e 's/\(^\*NickName.*\)"/\1 (foo2zjs recommended)"/'
+ 	done
+ 	;;
+-    update)
+-	url=${URLZJS}
+-	file=foo2zjs.tar.gz
+-	wget $WGETOPTS -O $file $url/$file ||
+-		error "Couldn't download $url/$exefile"
+-	mv getweb getweb.old
+-	HERE=`pwd`
+-	cd .. 
+-	tar zxf $HERE/$file
+-	cd $HERE
+-	echo "The tarball is extracted and the current directory is up to date."
+-	echo -e "Remove the tarball (y/n)? \c"
+-	read ans
+-	if [ "$ans" = y ]; then
+-	    rm -f $file
+-	fi
+-	;;
+     "")
+ 	usage
+ 	;;
+@@ -448,6 +470,10 @@
      usage
  fi
  
@@ -228,7 +261,7 @@ Improve getweb also for installing the firmware
  for i in $*
  do
      case "$1" in
-@@ -489,3 +534,6 @@
+@@ -489,3 +515,6 @@
  	;;
      esac
  done
